### ISSUE TITLE
Alternative for S25FL116K0XMFI041

### ISSUE THREAD

**Issue by stozze** [marqs85/ossc_pcb#5]
Hi,

First of all, thank you for making the OSSC open hardware/source, excellent work.

I've been busy soldering together an OSSC and today I finally got it completed and it worked like a charm, no magic smoke :). But I was not able to source the S25FL116K0XMFI041 (seems like these are no longer manufactured?) but I found a drop-in replacement that can be used instead, the IS25LP016D-JNLE, this one is more readily available and seems to work fine as a replacement, at least on the board I got up and running today, Quartus didn't complain about it either and programmed it just fine.

https://www.mouser.fi/ProductDetail/870-IS25LP016D-JNLE

So for the next version of the board maybe it would be better to use this one instead as it is more readily available?

**Comment by marqs85** [comment]
Updated BOM with the part in 35ba794.
