### ISSUE TITLE
OSSC_BOARD.WRL v1.5

### ISSUE THREAD

**Issue by Deneteus** [marqs85/ossc_pcb#6]
Howdy Marqs!

I need the OSSC_BOARD.WRL file from 1.5 or a 3D render of the 1.5 board with components. from the 1.5 Branch. Thanks in advance!

**Comment by marqs85** [comment]
I can generate WRL of the PCB itself, but there are no 3d models for manually created components. Basic components also may not map automatically to 3d models due to v1.5 having been done with old Kicad version which has different library format than Kicad 5.0.

**Comment by Deneteus** [comment]
That would work.

**Comment by marqs85** [comment]
WRL for v1.5-DIY is now uploaded [here](https://www.niksula.hut.fi/~mhiienka/ossc/diy-v1.5/pcb1.5-diy.wrl).
